### ISSUE TITLE
上传本地文件报错

### ISSUE THREAD

**Issue by HYQ307** [T3rry7f/Fake115Upload#5]
首先测试了个小文件，成功上传，说明配置成功；
然后试着上传个大体积的（5GB)，会报如下错误：

Traceback (most recent call last):
  File "/root/fake115upload.py", line 209, in <module>
    Upload_file_from_local(v)	
  File "/root/fake115upload.py", line 145, in Upload_file_from_local
    if Upload_localFile_whith_sha1(filename):
  File "/root/fake115upload.py", line 138, in Upload_localFile_whith_sha1
    sha.update(f.read())
MemoryError

另外那个从本地文件读取被封了；

**Comment by T3rry7f** [comment]
本地上传大文件还是用浏览器吧 导入功能已修复
