### ISSUE TITLE
使用报错，请问cookie是Chrome F12 抓取的直接调用吗

### ISSUE THREAD

**Issue by yanshibin** [T3rry7f/Fake115Upload#6]
python fake115upload.py -o 116.txt
Traceback (most recent call last):
  File "fake115upload.py", line 269, in <module>
    Export_115_sha1_to_file(v)
  File "fake115upload.py", line 223, in Export_115_sha1_to_file
    if (json.loads(r.content).has_key('data')):
AttributeError: 'dict' object has no attribute 'has_key'

**Comment by T3rry7f** [comment]
是的
