### ISSUE TITLE
指定cid目录时第87行ShowFolderPath函数报错KeyError: 'path'

### ISSUE THREAD

**Issue by LSD08KM** [T3rry7f/Fake115Upload#9]
```
D:\D\Fake115Upload>python2 fake115upload.py -c 1719011478452829559 -o 115s.txt
Traceback (most recent call last):
  File "fake115upload.py", line 270, in <module>
    ShowFolderPath(cid)
  File "fake115upload.py", line 87, in ShowFolderPath
    resp=json.loads(r.content)['path']
KeyError: 'path'
```
通过-c指定cid目录，line 87出错
尝试 
` 	print r.content`
`	print json.loads(r.content) `
发现没有path键名
```
{"count":94,"order":"file_name","is_asc":1,"fc_mix":0,"state":false,"error":"","errNo":20130827}
{u'count': 94, u'is_asc': 1, u'errNo': 20130827, u'fc_mix': 0, u'state': False, u'error': u'', u'order': u'file_name'}
```

临时解决办法是注释掉第270行 ShowFolderPath(cid)

**Comment by LSD08KM** [comment]
为什么直接把issue关了...
